services:
  - type: web
    name: tp3-back
    runtime: docker
    dockerfilePath: ./TP3/Dockerfile
    dockerContext: ./TP3
    plan: free
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: tp1-front
    runtime: static
    rootDir: ./TP1
    buildCommand: ""
    staticPublishPath: .
    plan: free