services:
  - type: web
    name: tp3-back
    runtime: node
    rootDir: TP3
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: tp1-front
    runtime: static
    rootDir: TP1
    buildCommand: ""
    staticPublishPath: .